apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossip-router
  labels:
    app: gossip-router
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gossip-router
  template:
    metadata:
      labels:
        app: gossip-router
    spec:
      containers:
        - name: gossip-router
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "java"
            - "-cp"
            - "/app/conf:/app/uber.jar"
            - "org.jgroups.stack.GossipRouter"
            - "-bindaddress"
            - "0.0.0.0"
            - "-port"
            - "{{ .Values.gossip.port }}"
          ports:
            - containerPort: {{ .Values.gossip.port }}
              protocol: TCP
