apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossip-router
  labels:
    app: gossip-router
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gossip-router
  template:
    metadata:
      labels:
        app: gossip-router
    spec:
      containers:
        - name: gossip-router
          image: "{{ .Values.global.vertx_playground.image.repository | default .Values.image.repository }}:{{ .Values.global.vertx_playground.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.vertx_playground.image.pullPolicy | default .Values.image.pullPolicy }}
          command:
            - "java"
            - "-cp"
            - "/app/conf:/app/uber.jar"
            - "org.jgroups.stack.GossipRouter"
            - "-bindaddress"
            - "0.0.0.0"
            - "-port"
            - "{{ .Values.gossip.port }}"
          resources:
            limits:
              cpu: "1000m"
              memory: "256Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.gossip.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 7000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7000
            initialDelaySeconds: 15
            periodSeconds: 10
