infinispan:
  deploy:
    replicas: 3

gossip-router:
  replicaCount: 6
  image:
    repository: "moonkev/vertx_playground"
    tag: "1.0"
    pullPolicy: Never
  gossip:
    port: 7000

fibonacci-bot:
  replicaCount: 1
  image:
    repository: "moonkev/vertx_playground"
    tag: "1.0"
    pullPolicy: Never
  mainclass: MainKt
  cluster:
    port: 5555

fibonacci-worker:
  replicaCount: 10
  image:
    repository: "moonkev/vertx_playground"
    tag: "1.0"
    pullPolicy: Never
  mainclass: MainInfinispanKt
  jgroups:
    port: 7800
  cluster:
    port: 5555

graphql-service:
  replicaCount: 2
  image:
    repository: "moonkev/vertx_playground"
    tag: "1.0"
    pullPolicy: Never
  mainclass: MainInfinispanKt
  jgroups:
    port: 7800
  cluster:
    port: 5555
  service:
    port: 8080

grpc-service:
  replicaCount: 2
  image:
    repository: "moonkev/vertx_playground"
    tag: "1.0"
    pullPolicy: Never
  mainclass: MainInfinispanKt
  jgroups:
    port: 7800
  cluster:
    port: 5555
  service:
    port: 8080

rest-service:
  replicaCount: 2
  image:
    repository: "moonkev/vertx_playground"
    tag: "1.0"
    pullPolicy: Never
  mainclass: MainInfinispanKt
  jgroups:
    port: 7800
  cluster:
    port: 5555
  service:
    port: 8080
