global:
  vertx_playground:
    image:
      repository: "moonkev/vertx_playground"
      tag: "latest"
      pullPolicy: Never

gossip-router:
  replicaCount: 1
  gossip:
    port: 7000

fibonacci-bot:
  replicaCount: 1
  mainclass: MainKt
  cluster:
    port: 5555

fibonacci-worker:
  replicaCount: 5
  mainclass: MainInfinispanKt
  jgroups:
    port: 7800
  cluster:
    port: 5555

rest-service:
  replicaCount: 1
  mainclass: MainInfinispanKt
  jgroups:
    port: 7800
  cluster:
    port: 5555
  service:
    port: 8080
    nodePort: 32630

graphql-service:
  replicaCount: 1
  mainclass: MainInfinispanKt
  jgroups:
    port: 7800
  cluster:
    port: 5555
  service:
    port: 8080
    nodePort: 32620

grpc-service:
  replicaCount: 1
  mainclass: MainInfinispanKt
  jgroups:
    port: 7800
  cluster:
    port: 5555
  service:
    port: 8080
    nodePort: 32630

