fibonacci-bot:
  replicaCount: 1
  image:
    repository: "moonkev/vertx_playground"
    tag: "1.0"
    pullPolicy: Never
  cluster:
    port: 5555

fibonacci-worker:
  replicaCount: 10
  image:
    repository: "moonkev/vertx_playground"
    tag: "1.0"
    pullPolicy: Never
  cluster:
    port: 5555

graphql-service:
  replicaCount: 2
  image:
    repository: "moonkev/vertx_playground"
    tag: "1.0"
    pullPolicy: Never
  cluster:
    port: 5555
  service:
    port: 8080

grpc-service:
  replicaCount: 2
  image:
    repository: "moonkev/vertx_playground"
    tag: "1.0"
    pullPolicy: Never
  cluster:
    port: 5555
  service:
    port: 8080

rest-service:
  replicaCount: 2
  image:
    repository: "moonkev/vertx_playground"
    tag: "1.0"
    pullPolicy: Never
  cluster:
    port: 5555
  service:
    port: 8080

zookeeper:
  replicaCount: 1
  image:
    repository: zookeeper
    tag: "3.8.4"
    pullPolicy: IfNotPresent
  service:
    port: 2181
