apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-bot
  labels:
    app: fibonacci-bot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fibonacci-bot
  template:
    metadata:
      labels:
        app: fibonacci-bot
    spec:
      initContainers:
        - name: wait-for-grpc-server
          image: "busybox:1.37.0-uclibc"
          imagePulPolicy: "IfNotPresent"
          command:
            [
              "sh",
              "-c",
              "until nc -z grpc-service 8080; do echo waiting for grpc service; sleep 2; done;"
            ]
      containers:
        - name: fibonacci-bot
          image: "{{ .Values.global.vertx_playground.image.repository | default .Values.image.repository }}:{{ .Values.global.vertx_playground.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.vertx_playground.image.pullPolicy | default .Values.image.pullPolicy }}
          command:
            - "java"
            - "-cp"
            - "/app/conf:/app/uber.jar"
            - "-Dconfig.path=/app/conf/fibonacci-bot.conf"
            - "-Dvertx.eventbus.port={{ .Values.cluster.port }}"
            - "-Dio.netty.allocator.centralQueueCapacity=2"
            - "io.github.moonkev.vertx_playground.{{ .Values.mainclass }}"
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
            requests:
              cpu: "1000m"
              memory: "512Mi"
          ports:
            - containerPort: {{ .Values.cluster.port }}
              protocol: TCP
