apiVersion: v1
kind: Service
metadata:
  name: fibonacci-bot
spec:
  selector:
    app: fibonacci-bot
  ports:
    - protocol: TCP
      port: {{ .Values.cluster.port }}
      targetPort: {{ .Values.cluster.port }}