replicaCount: 2
image:
  repository: "moonkev/vertx_playground"
  tag: "1.0"
  pullPolicy: Never
mainclass: MainInfinispanKt
cluster:
  port: 5555
service:
  port: 8080
  nodePort: 32620
jgroups:
  port: 7800
