apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-tools
  labels:
    app: network-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-tools
  template:
    metadata:
      labels:
        app: network-tools
    spec:
      containers:
        - name: network-tools
          image: "busybox:1.37.0-uclibc"
          imagePullPolicy: "IfNotPresent"
          command:
            - "nc"
            - "-l"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"