apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  selector:
    app: grpc-service
  ports:
    - name: "event-bus"
      protocol: TCP
      port: {{ .Values.cluster.port }}
      targetPort: {{ .Values.cluster.port }}
    - name: "grpc"
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
