apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-worker
  labels:
    app: fibonacci-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fibonacci-worker
  template:
    metadata:
      labels:
        app: fibonacci-worker
    spec:
      initContainers:
        - name: wait-for-gossip-router
          image: {{ .Values.global.busybox.image | default "busybox" }}
          command:
            [
              "sh",
              "-c",
              "until nc -z gossip-router 7000; do echo waiting for gossip router; sleep 2; done;"
            ]
      containers:
        - name: fibonacci-worker
          image: "{{ .Values.global.vertx_playground.image.repository | default .Values.image.repository }}:{{ .Values.global.vertx_playground.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.vertx_playground.image.pullPolicy | default .Values.image.pullPolicy }}
          command:
            - "java"
            - "-cp"
            - "/app/conf:/app/uber.jar"
            - "-Dconfig.path=/app/conf/fibonacci-worker.conf"
            - "-Dvertx.eventbus.port={{ .Values.cluster.port }}"
            - "-Dio.netty.allocator.centralQueueCapacity=2"
            - "io.github.moonkev.vertx_playground.{{ .Values.mainclass }}"
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
            requests:
              cpu: "1000m"
              memory: "512Mi"
          ports:
            - containerPort: {{ .Values.cluster.port }}
              protocol: TCP
            - containerPort: {{ .Values.jgroups.port }}
              protocol: TCP
