apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-worker
  labels:
    app: fibonacci-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fibonacci-worker
  template:
    metadata:
      labels:
        app: fibonacci-worker
    spec:
      containers:
        - name: fibonacci-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "java"
            - "-cp"
            - "/app/conf:/app/uber.jar"
            - "-Dconfig.file=/app/conf/fibonacci-worker.conf"
            - "-Dvertx.eventbus.port={{ .Values.cluster.port }}"
            - "com.github.moonkev.vertx_playground.MainKt"
          ports:
            - containerPort: {{ .Values.cluster.port }}
              protocol: TCP
