name: vertx_playground

services:
#  gossip-router:
#    image: moonkev/vertx_playground:1.0
#    command:
#      - "java"
#      - "-cp"
#      - "/app/conf:/app/uber.jar"
#      - "org.jgroups.stack.GossipRouter"
#      - "-bindaddress"
#      - "0.0.0.0"
#      - "-port"
#      - "7000"
#    expose:
#      - "7000"

  fibonacci-worker:
    image: moonkev/vertx_playground:1.0
    command:
      - "java"
      - "-cp"
      - "/app/conf:/app/uber.jar"
      - "-Dconfig.path=/app/conf/fibonacci-worker.conf"
      - "-Dvertx.eventbus.port=5555"
      - "io.github.moonkev.vertx_playground.MainInfinispanKt"
    expose:
      - "5555"
      - "7800"
    deploy:
      mode: replicated
      replicas: 6
    networks:
      default:
        aliases:
          - jgroups-cluster

  rest-service:
    image: moonkev/vertx_playground:1.0
    command:
      - "java"
      - "-cp"
      - "/app/conf:/app/uber.jar"
      - "-Dconfig.path=/app/conf/rest-service.conf"
      - "-Dvertx.eventbus.port=5555"
      - "io.github.moonkev.vertx_playground.MainInfinispanKt"
    depends_on:
      grpc-service:
        condition: service_started
        restart: true
    expose:
      - "5555"
      - "7800"
    ports:
      - "18080:8080"
    networks:
      default:
        aliases:
          - jgroups-cluster

  graphql-service:
    image: moonkev/vertx_playground:1.0
    command:
      - "java"
      - "-cp"
      - "/app/conf:/app/uber.jar"
      - "-Dconfig.path=/app/conf/graphql-service.conf"
      - "-Dvertx.eventbus.port=5555"
      - "io.github.moonkev.vertx_playground.MainInfinispanKt"
    depends_on:
      fibonacci-worker:
        condition: service_started
        restart: true
    expose:
      - "5555"
      - "7800"
    ports:
      - "28080:8080"
    networks:
      default:
        aliases:
          - jgroups-cluster

  grpc-service:
    image: moonkev/vertx_playground:1.0
    command:
      - "java"
      - "-cp"
      - "/app/conf:/app/uber.jar"
      - "-Dconfig.path=/app/conf/grpc-service.conf"
      - "-Dvertx.eventbus.port=5555"
      - "io.github.moonkev.vertx_playground.MainInfinispanKt"
    healthcheck:
      test: "/bin/curl -f http://localhost:8080/health"
      start_period: 5s
      interval: 15s
      timeout: 15s
      retries: 2
    depends_on:
      fibonacci-worker:
        condition: service_started
        restart: true
    expose:
      - "5555"
      - "7800"
    ports:
      - "38080:8080"
    networks:
      default:
        aliases:
          - jgroups-cluster

  fibonacci-bot:
    image: moonkev/vertx_playground:1.0
    command:
      - "java"
      - "-cp"
      - "/app/conf:/app/uber.jar"
      - "-Dconfig.path=/app/conf/fibonacci-bot.conf"
      - "io.github.moonkev.vertx_playground.MainKt"
    depends_on:
      grpc-service:
        condition: service_healthy
        restart: true
    deploy:
      mode: replicated
      replicas: 1
