replicaCount: 2
image:
  repository: "moonkev/vertx_playground"
  tag: "1.0"
  pullPolicy: Never
mainclass: MainInfinispanKt
cluster:
  port: 5555
service:
  port: 8080
jgroups:
  port: 7800
resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
