apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-service
  labels:
    app: graphql-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: graphql-service
  template:
    metadata:
      labels:
        app: graphql-service
    spec:
      initContainers:
        - name: wait-for-gossip-router
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z gossip-router 7000; do echo waiting for gossip router; sleep 2; done;"
            ]
      containers:
        - name: graphql-service
          image: "{{ .Values.global.vertx_playground.image.repository | default .Values.image.repository }}:{{ .Values.global.vertx_playground.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.vertx_playground.image.pullPolicy | default .Values.image.pullPolicy }}
          command:
            - "java"
            - "-cp"
            - "/app/conf:/app/uber.jar"
            - "-Dconfig.path=/app/conf/graphql-service.conf"
            - "-Dvertx.eventbus.port={{ .Values.cluster.port }}"
            - "-Dio.netty.allocator.centralQueueCapacity=2"
            - "io.github.moonkev.vertx_playground.{{ .Values.mainclass }}"
          ports:
            - containerPort: {{ .Values.jgroups.port }}
              protocol: TCP
            - containerPort: {{ .Values.cluster.port }}
              protocol: TCP
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
