apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-service
  labels:
    app: graphql-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: graphql-service
  template:
    metadata:
      labels:
        app: graphql-service
    spec:
      containers:
        - name: graphql-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "java"
            - "-cp"
            - "/app/conf:/app/uber.jar"
            - "-Dconfig.path=/app/conf/graphql-service.conf"
            - "-Dvertx.eventbus.port={{ .Values.cluster.port }}"
            - "com.github.moonkev.vertx_playground.{{ .Values.mainclass }}"
          ports:
            - containerPort: {{ .Values.jgroups.port }}
              protocol: TCP
            - containerPort: {{ .Values.cluster.port }}
              protocol: TCP
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
