apiVersion: v1
kind: Service
metadata:
  name: graphql-service-event-buss
spec:
  selector:
    app: graphql-service
  ports:
    - name: "event-bus"
      protocol: TCP
      port: {{ .Values.cluster.port }}
      targetPort: {{ .Values.cluster.port }}
