apiVersion: v1
kind: Service
metadata:
  name: graphql-service
spec:
  selector:
    app: graphql-service
  type: NodePort
  ports:
    - name: "graphql"
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
