apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphql-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: graphql.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: graphql-service
                port:
                  number: 8080