apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service
  labels:
    app: rest-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rest-service
  template:
    metadata:
      labels:
        app: rest-service
        deploymentConfig: jgrp
    spec:
      containers:
        - name: rest-service
          image: "{{ .Values.global.vertx_playground.image.repository | default .Values.image.repository }}:{{ .Values.global.vertx_playground.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.vertx_playground.image.pullPolicy | default .Values.image.pullPolicy }}
          command:
            - "java"
            - "-cp"
            - "/app/conf:/app/uber.jar"
            - "-Dconfig.path=/app/conf/rest-service.conf"
            - "-Dvertx.eventbus.port={{ .Values.cluster.port }}"
            - "-Djgroups.dns_ping.dns_query=_ping._tcp.jgrp.vertx-playground.svc.cluster.local"
            - "-Dio.netty.allocator.centralQueueCapacity=2"
            - "io.github.moonkev.vertx_playground.{{ .Values.mainclass }}"
          resources:
            limits:
              cpu: "1000m"
              memory: "256Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.jgroups.port }}
              protocol: TCP
            - containerPort: {{ .Values.cluster.port }}
              protocol: TCP
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
